repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks # General
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform # Terraform and terragrunt
    rev: v1.96.1
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terragrunt_fmt
      - id: terragrunt_providers_lock
      - id: terragrunt_validate
      - id: terragrunt_validate_inputs
  - repo: https://github.com/python-jsonschema/check-jsonschema # GitHub Actions
    rev: 0.29.4
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/crate-ci/typos
    rev: v1.27.0
    hooks:
      - id: typos
